name: Laravel

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]
env:
  LARAVEL_BYPASS_ENV_CHECK: 1
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: testing
        DB_DATABASE: database/database.sqlite
        LARAVEL_BYPASS_ENV_CHECK: 1
      run: php artisan test --coverage --min=75
  npm-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          env:
            LARAVEL_BYPASS_ENV_CHECK: 1
          with:
            node-version: ${{ matrix.node-version }}
            cache: "npm"
        - name: Run npm install
          run: npm install
        - name: Execute Unit tests
          run: npm run check